### ISSUE TITLE
[Home] Agregar texto al slider

### ISSUE THREAD

**Issue by jpverdejo** [mortegac/PROYECTO-FULLSTACK#1]
El slider no tiene los textos del diseño:

Diseño:
<img width="746" alt="screen shot 2015-10-10 at 12 24 28 pm" src="https://cloud.githubusercontent.com/assets/1238288/10411862/63072d88-6f52-11e5-8f81-aada9a06156d.png">

TP:
<img width="1266" alt="screen shot 2015-10-10 at 12 22 27 pm" src="https://cloud.githubusercontent.com/assets/1238288/10411851/ffa4050e-6f51-11e5-9d28-2d75e3d83dd7.png">

**Comment by mortegac** [comment]
SOLUCIONADO con COMMIT b8b21664fc4d7422ff5be4afa5c26c8c570d7a91
