### ISSUE TITLE
[Home] En la seccion "Hostro services" el titulo de los servicios esta des-centrado

### ISSUE THREAD

**Issue by jpverdejo** [mortegac/PROYECTO-FULLSTACK#4]
El titulo de los servicios tiene que estar alineado a la imagen:

Diseño:
<img width="199" alt="screen shot 2015-10-10 at 12 30 21 pm" src="https://cloud.githubusercontent.com/assets/1238288/10411888/2d556302-6f53-11e5-8cbc-67e88e02d2cd.png">

TP:
<img width="393" alt="screen shot 2015-10-10 at 12 30 16 pm" src="https://cloud.githubusercontent.com/assets/1238288/10411889/30167f68-6f53-11e5-9683-2b9907cc720c.png">

**Comment by mortegac** [comment]
Centrado 5b12a0adb843ee51d0839f39dda33a2995a3382a
