### ISSUE TITLE
[Home] Body con ancho < 100%

### ISSUE THREAD

**Issue by jpverdejo** [mortegac/PROYECTO-FULLSTACK#7]
Al tener un ancho menor a 100% se ve un color plomo de fondo en este navegador. Body siempre tiene que tener ancho 100%.

<img width="1280" alt="screen shot 2015-10-10 at 12 35 51 pm" src="https://cloud.githubusercontent.com/assets/1238288/10411912/da56bc90-6f53-11e5-9d74-0f3d7bb0aa6a.png">

**Comment by mortegac** [comment]
Resuelto c7e6cf31661ac608419e52de4cc8b39473e09137
